all: admission department student

admission: Admission.cpp 
	g++ -o admission Admission.cpp -lnsl -lresolv

department: Department.cpp
	g++ -o department Department.cpp -lnsl -lresolv

student:	Student.cpp
	g++ -o student Student.cpp -lnsl -lresolv